import{a as b,S as f,i as c}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="48303483-31cfd41ec7662904a2a6a727b",v="https://pixabay.com/api/";async function g(t,r=1,o=15){const i=`${v}?key=${L}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${o}`,e=await b.get(i);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}function p({webformatURL:t,largeImageURL:r,tags:o,likes:i,views:e,comments:s,downloads:n}){return`
    <a href="${r}" class="gallery-item" title="${o}">
      <img src="${t}" alt="${o}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes</b>${i}</p>
        <p class="info-item"><b>Views</b>${e}</p>
        <p class="info-item"><b>Comments</b>${s}</p>
        <p class="info-item"><b>Downloads</b>${n}</p>
      </div>
    </a>
  `}function $(t){const r=document.querySelector(".gallery");r.innerHTML=t.map(p).join(""),new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}function w(t){document.querySelector(".gallery").insertAdjacentHTML("beforeend",t.map(p).join("")),new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}const E=document.querySelector("#search-form"),m=document.querySelector(".gallery"),l=document.querySelector("#load-more-btn"),a=document.createElement("div");a.classList.add("loader","hidden");document.body.appendChild(a);let d=1,u="",h=0;E.addEventListener("submit",async t=>{if(t.preventDefault(),u=t.currentTarget.elements.searchQuery.value.trim(),!u){c.error({title:"Error",message:"Please enter a search query"});return}t.currentTarget.reset();try{a.classList.remove("hidden"),m.innerHTML="",d=1;const r=await g(u,d);if(h=r.totalHits,a.classList.add("hidden"),r.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}$(r.hits),h>15?l.classList.remove("hidden"):l.classList.add("hidden"),y(m)}catch(r){c.error({title:"Error",message:r.message}),a.classList.add("hidden")}});l.addEventListener("click",async()=>{try{d+=1,a.classList.remove("hidden");const t=await g(u,d);w(t.hits),a.classList.add("hidden"),d*15>=h?(l.classList.add("hidden"),c.error({title:"Info",message:"We're sorry, but you've reached the end of search results."})):l.classList.remove("hidden"),y(m)}catch(t){c.error({title:"Error",message:t.message}),a.classList.add("hidden")}});function y(t){const{height:r}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
